package edu.moravian.csci395.carman.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF3A5F7A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFCCE5F6)
val onPrimaryContainerLight = Color(0xFF001E2F)
val secondaryLight = Color(0xFF4E616E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCCDEEB)
val onSecondaryContainerLight = Color(0xFF0A2533)
val surfaceVariantLight = Color(0xFFDCE8F0)
val onSurfaceVariantLight = Color(0xFF3A5061)
val surfaceContainerLight = Color(0xFFE8F1F7)
val surfaceContainerHighestLight = Color(0xFFD4E3EE)
val backgroundLight = Color(0xFFF6FAFD)
val surfaceLight = Color(0xFFF6FAFD)

val primaryDark = Color(0xFFA3CBE6)
val onPrimaryDark = Color(0xFF003349)
val primaryContainerDark = Color(0xFF004863)
val onPrimaryContainerDark = Color(0xFFCBE6FF)
val secondaryDark = Color(0xFFB5C9D7)
val onSecondaryDark = Color(0xFF20333E)
val secondaryContainerDark = Color(0xFF2A4050)
val onSecondaryContainerDark = Color(0xFFD1E4F0)
val surfaceVariantDark = Color(0xFF1E2D36)
val onSurfaceVariantDark = Color(0xFFB0C5D2)
val surfaceContainerDark = Color(0xFF1A2730)
val surfaceContainerHighestDark = Color(0xFF243340)
val backgroundDark = Color(0xFF101417)
val surfaceDark = Color(0xFF101417)
